name: Deploy EC2

on:
  push:
    branches:
      - "main"

jobs:
  connect_ssh:
    name: connect_ssh
    runs-on: ubuntu-latest
    environment:
      name: staging 
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.2
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: whoami
